kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: grafana-secrets
    annotations:
      reloader.stakater.com/auto: "true"
env:
  secretMap:
    admin-password: "sandbox/grafana/password"
    admin-user: "sandbox/grafana/user"