apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore
spec:
  provider:
    fake:
      data:
      - key: "/db/password"
        value: "password-v1"
        version: "v1"
      - key: "/db/password"
        value: "password-v2"
        version: "v2"