apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-es
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
  {{- range $name, $value := .Values.env.secretMap }}
  - secretKey: {{ $name }}
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ required (printf "key %s is missing from .Values.secretMap" $name) $value | quote}}
  {{- end }}
