apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "echo-server.fullname" . }}-es
spec:
  refreshInterval: 5s #use something more meaningful in production
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ template "echo-server.fullname" . }}
    creationPolicy: Owner
  data:
  # - secretKey: DATASCRIPT_DATABASE_PASSWORD
  #   remoteRef:
  #     key: "/db/password"
  #   version: v1
{{ toYaml .Values.secrets | indent 4}}